name: twemoji_v2
description: Twemoji for Flutter based on Twemoji 14.1.2 - Supports SVG
version: 0.5.3
homepage: https://github.com/DynxstyGIT/twemoji_v2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  characters: ^1.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  io: ^1.0.3

  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/svg/
